/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WmTypeRouteImport } from './routes/wm.$type'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ConfigIdRouteImport } from './routes/config.$id'
import { Route as ApiGithubInitiateRouteImport } from './routes/api.github.initiate'
import { Route as ApiGithubCallbackRouteImport } from './routes/api.github.callback'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WmTypeRoute = WmTypeRouteImport.update({
  id: '/wm/$type',
  path: '/wm/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIdRoute = ConfigIdRouteImport.update({
  id: '/config/$id',
  path: '/config/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInitiateRoute = ApiGithubInitiateRouteImport.update({
  id: '/api/github/initiate',
  path: '/api/github/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/upload': typeof UploadRoute
  '/config/$id': typeof ConfigIdRoute
  '/u/$username': typeof UUsernameRoute
  '/wm/$type': typeof WmTypeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/initiate': typeof ApiGithubInitiateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/upload': typeof UploadRoute
  '/config/$id': typeof ConfigIdRoute
  '/u/$username': typeof UUsernameRoute
  '/wm/$type': typeof WmTypeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/initiate': typeof ApiGithubInitiateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/upload': typeof UploadRoute
  '/config/$id': typeof ConfigIdRoute
  '/u/$username': typeof UUsernameRoute
  '/wm/$type': typeof WmTypeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/initiate': typeof ApiGithubInitiateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/donate'
    | '/upload'
    | '/config/$id'
    | '/u/$username'
    | '/wm/$type'
    | '/api/github/callback'
    | '/api/github/initiate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/donate'
    | '/upload'
    | '/config/$id'
    | '/u/$username'
    | '/wm/$type'
    | '/api/github/callback'
    | '/api/github/initiate'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/donate'
    | '/upload'
    | '/config/$id'
    | '/u/$username'
    | '/wm/$type'
    | '/api/github/callback'
    | '/api/github/initiate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DonateRoute: typeof DonateRoute
  UploadRoute: typeof UploadRoute
  ConfigIdRoute: typeof ConfigIdRoute
  UUsernameRoute: typeof UUsernameRoute
  WmTypeRoute: typeof WmTypeRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInitiateRoute: typeof ApiGithubInitiateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wm/$type': {
      id: '/wm/$type'
      path: '/wm/$type'
      fullPath: '/wm/$type'
      preLoaderRoute: typeof WmTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$id': {
      id: '/config/$id'
      path: '/config/$id'
      fullPath: '/config/$id'
      preLoaderRoute: typeof ConfigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/initiate': {
      id: '/api/github/initiate'
      path: '/api/github/initiate'
      fullPath: '/api/github/initiate'
      preLoaderRoute: typeof ApiGithubInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DonateRoute: DonateRoute,
  UploadRoute: UploadRoute,
  ConfigIdRoute: ConfigIdRoute,
  UUsernameRoute: UUsernameRoute,
  WmTypeRoute: WmTypeRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInitiateRoute: ApiGithubInitiateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
